### ISSUE TITLE
Public fc private fcrepo uris

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/pass-doi-service#2]
When calling the service from pass-ember, I get private fcrepo container URI instead of the public URI returned in the result.

**Comment by markpatton** [comment]
Should be able to use these variables in the .env:
`PASS_FEDORA_BASEURL=http://fcrepo:8080/fcrepo/rest/` `PASS_EXTERNAL_FEDORA_BASEURL=https://pass.local/fcrepo/rest/`

**Comment by jrmartino** [comment]
this was addresss in  PR#3
