### ISSUE TITLE
Incorrect Documentation (Service URL)

### ISSUE THREAD

**Issue by derekbelrose** [eclipse-pass/pass-doi-service#5]
The service throws 404s when going to http://${HOST}:${PORT}/journal

It seems the service is actually deployed at http://${HOST}:${PORT}/pass-doi-service according to the tomcat logs.

**Comment by rpoet-jh** [comment]
The migration of PASS repositories to eclipse-pass is complete. This issue is no longer relevant and is being closed as part of archiving https://github.com/eclipse-pass/main/issues/585.
